namespace ProjectEuler.Problems
{
    public class Problem2 : Problem
    {
        public Problem2()
        {
            Id = 2;
            Name = "Even Fibonacci Numbers";
            Description =
                "    Each new term in the Fibonacci sequence is generated by adding the previous\n" +
                "    two terms. By starting with 1 and 2, the first terms will be:\n\n" +
                "        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n\n" +
                "    By considering the terms in the Fibonacci sequence whose values do not\n" +
                "    exceed four million, find the sum of the even-valued terms.";
        }

        public override string GetSolution()
        {
            int sum = 0;
            int fib1 = 0;
            int fib2 = 1;
            int fibNext = 1;

            while (fibNext < 4000000)
            {
                if (fibNext % 2 == 0)
                    sum += fibNext;

                fib1 = fib2;
                fib2 = fibNext;
                fibNext = fib1 + fib2;
            }

            return sum.ToString();
        }
    }
}
